### PR TITLE
Make site/dist-packages robust

### PR DESCRIPTION
**Pull request by askiiart**
This finds the location of site-packages (or dist-packages), and uses that to copy the dependencies to, rather than `/usr/local/lib/python3.7/dist-packages` (or whatever it is). 

This is a fairly simple edit, so it should work, but please test this before accepting to make sure (I'd test it, but I don't use Kaggle). By the way, I also cleaned up some of the code for you :wink:

### CODE REVIEW

**Review by tuwonga — COMMENTED** [review]
into the fast-dreambooth-textencoder did you forgot the cell
`# Find site-packages (note: can't be named site-packages)
from subprocess import getoutput
site_packages = getoutput('pip show torch')
site_packages = site_packages[site_packages.find('Location:')+10:]
site_packages = site_packages[:site_packages.find('\n')]`  ???

**Review by tuwonga — APPROVED** [review]

**Comment by tuwonga** [comment]
waiting for your fix, after that I will merge

**Comment by askiiart** [comment]
> waiting for your fix, after that I will merge

Sounds good. Expect a fix in ~5 hours

**Comment by tuwonga** [comment]
> > waiting for your fix, after that I will merge
> 
> Sounds good. Expect a fix in ~5 hours

the v2 only, the others were reviewed ;)
thank you!

**Comment by askiiart** [comment]
@tuwonga It should work now

**Comment by tuwonga** [comment]
> @tuwonga It should work now

please switch the magic % with !
Kaggle has issue on some lines.

Thank you

**Comment by askiiart** [comment]
> please switch the magic % with ! 
> Kaggle has issue on some lines.

Sorry about that, apparently Kaggle's interpreter works differently from stock Jupyter. On the `pip` lines?

**Comment by tuwonga** [comment]
> > please switch the magic % with !
> > Kaggle has issue on some lines.
> 
> Sorry about that, apparently Kaggle's interpreter works differently from stock Jupyter. On the `pip` lines?

yes, on the pip lines ;)
thank you

**Comment by tuwonga** [comment]
"This branch has conflicts that must be resolved" ???

**Comment by askiiart** [comment]
> "This branch has conflicts that must be resolved" ???

Yup, it can't be merged automatically. I'm back at my main PC now, so I'll just fix that for you. 
You should probably learn how to fix merge conflicts sometime, though. I'd be happy to teach you, if you'd like.

**Comment by askiiart** [comment]
@tuwonga You can merge it now!

**Comment by tuwonga** [comment]
> @tuwonga You can merge it now!

I really thank you for your work !!!!

**Pull request merged**
